// This file is automatically generated. Do not edit it directly.
import { createClient, type AuthChangeEvent, type Session, type SupabaseClient, type User } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const STORAGE_KEY = "smart-farm-guardian-demo-session";
const hasBrowserStorage = typeof window !== "undefined" && typeof window.localStorage !== "undefined";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const randomId = () => {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return Math.random().toString(36).slice(2);
};

const loadStoredSession = (): Session | null => {
  if (!hasBrowserStorage) return null;
  const raw = window.localStorage.getItem(STORAGE_KEY);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Session;
  } catch {
    window.localStorage.removeItem(STORAGE_KEY);
    return null;
  }
};

const persistSession = (session: Session | null) => {
  if (!hasBrowserStorage) return;
  if (session) {
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(session));
  } else {
    window.localStorage.removeItem(STORAGE_KEY);
  }
};

const buildMockUser = (email: string): User => {
  const timestamp = new Date().toISOString();
  return {
    id: `mock-${randomId()}`,
    aud: "authenticated",
    email,
    phone: "",
    created_at: timestamp,
    email_confirmed_at: timestamp,
    last_sign_in_at: timestamp,
    role: "authenticated",
    confirmed_at: timestamp,
    updated_at: timestamp,
    app_metadata: { provider: "mock" },
    user_metadata: { demo: true },
    identities: [],
    factors: [],
    is_anonymous: false,
    phone_confirmed_at: null,
    recovery_sent_at: null,
    invited_at: null,
  } as User;
};

const buildMockSession = (user: User): Session => {
  const expiresIn = 3600;
  const expiresAt = Math.floor(Date.now() / 1000) + expiresIn;
  return {
    access_token: randomId(),
    refresh_token: randomId(),
    token_type: "bearer",
    user,
    expires_in: expiresIn,
    expires_at: expiresAt,
    provider_token: null,
    provider_refresh_token: null,
  } as Session;
};

const createMockSupabaseClient = (): SupabaseClient<Database> => {
  type Listener = (event: AuthChangeEvent, session: Session | null) => void;
  const listeners = new Set<Listener>();

  const notify = (event: AuthChangeEvent, session: Session | null) => {
    listeners.forEach((listener) => listener(event, session));
  };

  const ensureSession = (email: string) => {
    const user = buildMockUser(email);
    const session = buildMockSession(user);
    persistSession(session);
    notify("SIGNED_IN", session);
    return session;
  };

  const mockAuth = {
    async getSession() {
      return { data: { session: loadStoredSession() }, error: null };
    },
    async getUser() {
      const session = loadStoredSession();
      return { data: { user: session?.user ?? null }, error: null };
    },
    onAuthStateChange(callback: Listener) {
      listeners.add(callback);
      const session = loadStoredSession();
      callback(session ? "SIGNED_IN" : "SIGNED_OUT", session);
      return {
        data: {
          subscription: {
            unsubscribe: () => {
              listeners.delete(callback);
            },
          },
        },
        error: null,
      };
    },
    async signUp({ email }: { email: string }) {
      const session = ensureSession(email);
      return { data: { user: session.user, session }, error: null };
    },
    async signInWithPassword({ email }: { email: string }) {
      const session = ensureSession(email);
      return { data: { user: session.user, session }, error: null };
    },
    async signOut() {
      persistSession(null);
      notify("SIGNED_OUT", null);
      return { error: null };
    },
    async updateUser() {
      const session = loadStoredSession();
      return { data: { user: session?.user ?? null }, error: null };
    },
    async signInWithOAuth({ provider }: { provider: string }) {
      // For mock, just generate a session as if the OAuth succeeded immediately
      const session = ensureSession("mock-oauth-user@example.com");
      return { data: { session, url: null, provider }, error: null };
    },
  };

  return {
    auth: mockAuth,
  } as unknown as SupabaseClient<Database>;
};

// Fallback to mock client if the URL is unreachable or for demo purposes
// To use real Supabase, ensure VITE_SUPABASE_URL points to a valid project
const useRealClient = false; // Set to true when valid credentials are provided

const supabaseClient =
  useRealClient && SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: hasBrowserStorage ? window.localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
    : createMockSupabaseClient();

export const supabase = supabaseClient;